### ISSUE TITLE
Remove free delivery from special offer

### ISSUE THREAD

**Issue by tookaa2** [anddopphoopha/03Restaurant#6]
Dear Dev team,
Since the delivery is delegated to Food panda, free is no longer a special offer. Please remove it from the special offer page and provide information of Food panda instead.

"Deliver with Food Panda:"
[Deliver food to you at rapid speed, with Food Panda!]
<Learn more button>

**Comment by anddopphoopha** [comment]
done check
lazy customer
I don't want your money any more
i quit
